# --- Site basics ---
locale: "en-US"
title: ""          # leave empty to hide Cayman's big blue header text
description: ""    # leave empty too
name: "Meisam Mohammady"
url: https://meisamcs.github.io
baseurl: ""
repository: "meisamcs/meisamcs.github.io"
timezone: America/Chicago

# --- Theme ---
remote_theme: pages-themes/cayman@v0.2.0
# (For local builds, you may need: jekyll-remote-theme)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# --- Author ---
author:
  name: "Meisam Mohammady"
  avatar: "meisam.png"  # put profilepic.jpg in the root of your repo
  bio: "Address: 2434 Osborn Dr, Department of Computer Science, Iowa State University, Ames, IA, 50011 <br><b>Office: 232 Atanasoff Hall</b><br><b>E-mail: meisam@iastate.edu</b>"
  googlescholar: "https://scholar.google.ca/citations?user=UL-3sUgAAAAJ&hl=en"

# --- Markdown Rendering ---
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
excerpt_separator: "\n\n"

# --- Defaults (Cayman layout only) ---
defaults:
  - scope:
      path: ""
    values:
      layout: default

# --- Compression ---
compress_html:
  clippings: none
  ignore:
    envs: development
