locale: "en-US"
title: ""
description: ""
name: "Meisam Mohammady"
url: https://meisamcs.github.io
baseurl: ""
repository: "meisamcs/meisamcs.github.io"
timezone: America/Chicago

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
excerpt_separator: "\n\n"

# keep _pages working on GitHub Pages (safe mode)
include:
  - _pages
  - _posts

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_pages"
    values:
      layout: default
      permalink: /:basename/
  - scope:
      path: "_posts"
    values:
      layout: default
      permalink: /blog/:year/:month/:day/:title/
